/**
 * One-page A4 resume, generated in the visitor's browser from data/resume.json.
 *
 * The layout deliberately matches career/build_tailored_resumes.py -- same A4
 * page, same 37/29pt margins, same Helvetica sizes -- so a resume assembled
 * here and one Eileen generated by hand are the same document. Helvetica is a
 * PDF base-14 font, so nothing is embedded and no font file has to load.
 *
 * The one-page rule is enforced, not hoped for: blocks are measured before
 * anything is drawn, spacing is compressed within a fixed range to make them
 * fit, and if that is not enough the last project is dropped rather than a
 * second page appearing. build() reports what it had to do in .fit.
 *
 * Nothing here writes text. Every string comes from data/resume.json, which
 * comes from the CV. Selection varies by role; the words never do.
 */
(function () {
  "use strict";

  var PAGE = { w: 595.28, h: 841.89, left: 37, right: 37, top: 29, bottom: 29 };
  var CONTENT_W = PAGE.w - PAGE.left - PAGE.right;
  var CONTENT_H = PAGE.h - PAGE.top - PAGE.bottom;
  var LINK = "#174e7a";

  // size / leading / space-before / space-after, in points.
  var S = {
    name:    { size: 20,  lead: 23,   before: 0, after: 4, bold: true,  align: "center" },
    contact: { size: 9,   lead: 11.5, before: 0, after: 2, bold: false, align: "center" },
    role:    { size: 10,  lead: 12.5, before: 5, after: 7, bold: true,  align: "center" },
    body:    { size: 9.5, lead: 12,   before: 0, after: 3, bold: false },
    head:    { size: 10.5,lead: 13,   before: 7, after: 4, bold: true  },
    title:   { size: 9.8, lead: 12,   before: 3, after: 2, bold: true  },
    meta:    { size: 8.8, lead: 11,   before: 0, after: 3, bold: false, grey: true },
    bullet:  { size: 9.5, lead: 12,   before: 0, after: 2, bold: false, indent: 9 },
  };

  // How far leading may be squeezed before dropping content instead. 0.90 puts
  // body leading at 10.8pt on 9.5pt text -- tight, still typeset. Below that
  // the descenders start meeting the next line's ascenders, so content gives
  // way instead of the typography.
  var DENSITY_MIN = 0.9;
  var DENSITY_STEP = 0.02;

  function font(doc, style) {
    doc.setFont("helvetica", style.bold ? "bold" : "normal");
    doc.setFontSize(style.size);
  }

  /** Wrap one block's text and return its lines plus the height it will take. */
  function measure(doc, block, density) {
    var style = S[block.style];
    font(doc, style);
    var width = CONTENT_W - (style.indent || 0);
    var lines = doc.splitTextToSize(block.text, width);
    var height = lines.length * style.lead * density +
                 (style.before + style.after) * density;
    return { lines: lines, height: height, style: style, links: block.links };
  }

  function measureAll(doc, blocks, density) {
    var total = 0;
    var measured = blocks.map(function (b) {
      var m = measure(doc, b, density);
      total += m.height;
      return m;
    });
    return { measured: measured, total: total };
  }

  /**
   * Blocks for one resume. `sel` is the already-resolved selection:
   * { roleLabel, projects: [...], languages: [...], tools: [...],
   *   experience: [...] }.
   */
  function blocksFor(data, sel) {
    var p = data.profile;
    var out = [];
    // links: [{ text, url }] -- each is drawn in the link colour and made
    // clickable wherever that exact text lands, wrapping included.
    function add(style, text, links) {
      out.push({ style: style, text: text, links: links || null });
    }

    add("name", p.name);
    add("contact", p.citizenship + " | " + data.education.location);
    add("contact", p.email + " | " + p.phone + " | LinkedIn | GitHub",
        [{ text: "LinkedIn", url: p.linkedin }, { text: "GitHub", url: p.github }]);
    add("role", sel.roleLabel);

    // Null unless Eileen writes one. It is the same on every variant.
    if (data.summary) add("body", data.summary);

    add("head", "EDUCATION");
    add("title", data.education.institution);
    add("body", data.education.degree + " | Expected graduation: " + data.education.graduation);
    data.education.detail.forEach(function (d) { add("meta", d); });

    // data.length is a page-budget setting applied to every variant alike --
    // never per role, per industry, or per visitor. See the note in
    // scripts/build_resume_json.py for why one page needs the shorter wording.
    var condensed = data.length === "condensed";

    add("head", "EXPERIENCE");
    sel.experience.forEach(function (job) {
      add("title", job.role + " | " + job.organisation);
      add("meta", job.dates + " | " + job.location);
      var bullets = condensed && job.bulletsCondensed ? job.bulletsCondensed : job.bullets;
      bullets.forEach(function (b) { add("bullet", "•  " + b); });
    });

    add("head", "SELECTED PROJECTS");
    sel.projects.forEach(function (proj) {
      add("title", proj.title);
      // Two projects have no GitHub URL on the CV (see TODO.md); those get no
      // link rather than a dead one.
      add("meta", proj.tools.join(", ") + " | " + proj.date +
                  (proj.url ? " | View project" : ""),
          proj.url ? [{ text: "View project", url: proj.url }] : null);
      proj.bullets.forEach(function (b) { add("bullet", "•  " + b); });
    });

    add("head", "TECHNICAL SKILLS");
    add("body", "Languages: " + sel.languages.join(", "));
    add("body", "Tools: " + sel.tools.join(", "));

    add("head", "CERTIFICATIONS");
    var certs = data.certifications.map(function (c) {
      return c.title + (c.date ? " | " + c.date : "");
    });
    if (condensed) {
      // Joined into one paragraph rather than trimmed. Five separate lines
      // cost their spacing five times over; running them together reclaims
      // most of that without dropping a certificate.
      add("meta", certs.join("  ·  "));
    } else {
      certs.forEach(function (c) { add("meta", c); });
    }

    return out;
  }

  /**
   * Draw one line, colouring and linking any declared link text inside it.
   *
   * Link geometry is derived from the line actually being drawn rather than
   * recomputed from the layout, so a wrapped line, a centred line and a
   * squeezed page all put the clickable rectangle where the words are.
   */
  function drawLine(doc, line, x0, y, style, links) {
    var baseColour = style.grey ? 51 : 0;
    var hit = null;
    if (links) {
      for (var i = 0; i < links.length && !hit; i++) {
        if (line.indexOf(links[i].text) !== -1) hit = links[i];
      }
    }
    var x = x0;
    if (style.align === "center") x = PAGE.w / 2 - doc.getTextWidth(line) / 2;

    if (!links || !hit) {
      doc.setTextColor(baseColour);
      doc.text(line, x, y);
      return;
    }

    // Draw the line in three runs so only the link text carries link colour.
    var cut = line.indexOf(hit.text);
    var parts = [
      { text: line.slice(0, cut), colour: baseColour },
      { text: hit.text, colour: LINK, url: hit.url },
      { text: line.slice(cut + hit.text.length), colour: baseColour },
    ];
    parts.forEach(function (part) {
      if (!part.text) return;
      var w = doc.getTextWidth(part.text);
      if (part.colour === LINK) doc.setTextColor(LINK);
      else doc.setTextColor(part.colour);
      doc.text(part.text, x, y);
      if (part.url) doc.link(x, y - style.size, w, style.size, { url: part.url });
      x += w;
    });
    doc.setTextColor(baseColour);

    // More than one link on a line (the contact line has two) -- the run above
    // consumed the first, so recurse over what is left of the line.
    var rest = links.filter(function (l) { return l !== hit; });
    var tail = line.slice(cut + hit.text.length);
    if (rest.length && tail.indexOf(rest[0].text) !== -1) {
      var tailX = x - doc.getTextWidth(tail);
      drawLine(doc, tail, tailX, y, { grey: style.grey, size: style.size, align: "left" }, rest);
    }
  }

  function draw(doc, measured, density) {
    var y = PAGE.top;
    measured.forEach(function (m) {
      var style = m.style;
      y += style.before * density;
      font(doc, style);
      m.lines.forEach(function (line, i) {
        y += style.lead * density;
        // Hanging indent: a bullet's wrapped lines sit under its text, not
        // under its dot.
        var x = i === 0 && style.indent ? PAGE.left : PAGE.left + (style.indent || 0);
        drawLine(doc, line, x, y, style, m.links);
      });
      y += style.after * density;
    });
    doc.setTextColor(0);
  }

  /**
   * Work out what actually fits on one page, without drawing anything.
   *
   * The preview on resume.html calls this too, so what a visitor is told is on
   * their PDF is what the PDF has. Squeeze the leading first; drop a project
   * only when squeezing has run out.
   */
  function fit(data, sel) {
    var jsPDF = window.jspdf && window.jspdf.jsPDF;
    if (!jsPDF) throw new Error("jsPDF not loaded");

    var projects = sel.projects.slice();
    var dropped = [];
    for (;;) {
      var attempt = Object.assign({}, sel, { projects: projects });
      var doc = new jsPDF({ unit: "pt", format: "a4", compress: true });
      var blocks = blocksFor(data, attempt);
      var density = 1;
      var result = measureAll(doc, blocks, density);
      while (result.total > CONTENT_H && density > DENSITY_MIN) {
        density = Math.round((density - DENSITY_STEP) * 100) / 100;
        result = measureAll(doc, blocks, density);
      }
      if (result.total <= CONTENT_H || projects.length <= 1) {
        return {
          doc: doc,
          selection: attempt,
          measured: result.measured,
          density: density,
          projects: projects,
          dropped: dropped,
          overflowed: result.total > CONTENT_H,
        };
      }
      dropped.push(projects.pop());
    }
  }

  /** Build the PDF. Returns { doc, filename, fit }. */
  function build(data, sel) {
    var f = fit(data, sel);
    f.doc.setProperties({
      title: "Eileen Ip Resume - " + sel.roleLabel,
      author: data.profile.name,
      subject: sel.roleLabel + (sel.industryLabel ? " | " + sel.industryLabel : ""),
    });
    draw(f.doc, f.measured, f.density);
    f.pages = f.doc.getNumberOfPages();
    return {
      doc: f.doc,
      filename: "Eileen Ip - " + sel.roleLabel + " Resume.pdf",
      fit: f,
    };
  }

  window.ResumePDF = { build: build, fit: fit, PAGE: PAGE, CONTENT_H: CONTENT_H };
})();
